### ISSUE TITLE
Initial Commit

### ISSUE THREAD

**Issue by sirthxalot** [sirthxalot/laravel-matryoshka#1]
## Situation

At this point we will have an empty project, ready to get feed with some data. So lets begin to tackle down the default structure and prepare everything in order to get ready for development.

## Tasks

- [x] Add common project files.
- [x] Provide caching services.
- [x] Provide the caching service provider.
- [x] Add tests for package.
